#! /bin/bash

. ~/bash/bashinit
. ~/bash/exports
. ~/bash/prompt
. ~/bash/aliases

[[ -f /usr/share/autojump/autojump.sh ]] && . /usr/share/autojump/autojump.sh

[[ -f ~/localrc ]] && . ~/localrc

. ~/bash/final
