#! /bin/bash

export JAVA_HOME=/app/jdk1.8.0_251

export PATH=$HOME/bin:/app/consul:$JAVA_HOME/bin:/app/node-v12.18.0-linux-x64/bin:$PATH
export LC_NUMERIC="en_US.UTF-8"

# C/C++
export LD_LIBRARY_PATH=/usr/local/lib
# export CPLUS_INCLUDE_PATH=/usr/local/include:/usr/include
